### ISSUE TITLE
Great work!!!

### ISSUE THREAD

**Issue by JohnRSim** [jnordberg/yichan#1]
Not an issue just wanted to show my support!! 
Great job.

Also question - when you request a token you send heartbeat?

{msg_id: 257, token: 0, heartbeat: 1}

What does this do? 
I just send:
{"msg_id":257,"token":0}
and it returns a token.

Is there any difference between
{"msg_id":513}

and the AMBA
0x1000005  start quick record

**Comment by jnordberg** [comment]
Thanks!

> Also question - when you request a token you send heartbeat?
> {msg_id: 257, token: 0, heartbeat: 1}
> What does this do? 

I don't know tbh, that's how the iOS app does it so i copied that, haven't seen any heartbeat data on the sockets so i doubt it does much.

> Is there any difference between
> {"msg_id":513}
> and the AMBA
> 0x1000005 start quick record

The quick record records for n seconds and then stops, haven't played much with it since i'm mostly interested in still photos for time-lapse shooting.

**Comment by JohnRSim** [comment]
Great thanks :+1: 
Will experiment some more and keep an eye on this Repo :)

Currently just for android but this is the app I'm working on for VR 360 and Xiaomi Yi 
https://play.google.com/store/apps/details?id=com.digaset.brahma

I'm just working on the timelapse integration at the moment - so it will be interesting to see what you come up with.

**Comment by jnordberg** [comment]
Nice app! Do you have the source for it up somewhere?

Also if your experiments turn something up please share it :) I'll put up a wikipage on this repository with all the codes and what I've found out about them so far so we can gather all the knowledge in one place

**Comment by JohnRSim** [comment]
No source for it sorry.. 
It's a badly written app - but happy to share my knowledge to put it up on the wiki page..

**Comment by JohnRSim** [comment]
This is my collection of notes from what I've found from other developers also updates with your codes.

//error camera crashed
-101:

//Invalid Path
-26:

//Invalid Msg ID
-23:

//Setting not writable
-15:

//-14: msg 515 not available,
//setting remain unchanged
-14:

//Invalid value
-13:

//msg 2 needs more options
//invalid arguments
-9:

//not sure need to research.. invalid msg probably..
-7:

//Unauthorised
//issue with token.. request new token..
-4:

//Other Device Connected
//# seems to happen when the iOS app is connected to the camera
-3:

//File Not Found
-1:

//got this after trying to update a conf setting
//Should mean OK.
0:

//Get Single Setting from conf
//{"msg_id":1,"type":"video_resolution","token":1}
1:

//set camera settings etc or reboot power off etc.
//{"msg_id":2,"type":"video_resolution","param":"1920x1080 60P 16:9","token":1}
//{"msg_id":2,"type":"dev_reboot","param":"on"}
//{"msg_id":2,"type":"restore_factory_settings","param":"on"}
//"type" - Key you want to set
//"param" - Value from available choices
2:
/*
{ "rval": 0, "msg_id": 2 ,"type":"video_resolution","param":"1920x1080 60P 16:9"}
*/

//rval -14 = error

//read config settings
//{"msg_id":3,"token":1}
3:
/*
{ "rval": 0, "msg_id": 3, "param": [ { "camera_clock": "2015-04-07 02:32:29" }, { "video_standard": "NTSC" }, { "app_status": "idle" }, { "video_resolution": "1920x1080 60P 16:9" }, { "video_stamp": "off" }, { "video_quality": "S.Fine" }, { "timelapse_video": "off" }, { "capture_mode": "precise quality" }, { "photo_size": "16M (4608x3456 4:3)" }, { "photo_stamp": "off" }, { "photo_quality": "S.Fine" }, { "timelapse_photo": "60" }, { "preview_status": "on" }, { "buzzer_volume": "mute" }, { "buzzer_ring": "off" }, { "capture_default_mode": "precise quality" }, { "precise_cont_time": "60.0 sec" }, { "burst_capture_number": "7 p / s" }, { "restore_factory_settings": "on" }, { "led_mode": "all enable" }, { "dev_reboot": "on" }, { "meter_mode": "center" }, { "sd_card_status": "insert" }, { "video_output_dev_type": "tv" }, { "sw_version": "YDXJv22_1.0.7_build-20150330113749_b690_i446_s699" }, { "hw_version": "YDXJ_v22" }, { "dual_stream_status": "on" }, { "streaming_status": "off" }, { "precise_cont_capturing": "off" }, { "piv_enable": "off" }, { "auto_low_light": "on" }, { "loop_record": "off" }, { "warp_enable": "off" }, { "support_auto_low_light": "on" }, { "precise_selftime": "5s" }, { "precise_self_running": "off" }, { "auto_power_off": "5 minutes" }, { "serial_number": "xxxxx" }, { "system_mode": "capture" }, { "system_default_mode": "capture" }, { "start_wifi_while_booted": "off" }, { "quick_record_time": "0" }, { "precise_self_remain_time": "0" }, { "sdcard_need_format": "no-need" }, { "video_rotate": "off" } ] }
*/

//format card
4:

//check card space
//{"msg_id":5,"type":"free"}
//{"msg_id":5,"type":"total"}
//"type" - free or total
5:
/*
{ "rval": 0, "msg_id": 5, "param": 15146464 }
"param" - Free (Or total) space on sdcard in bytes
*/

//Status Updates type [battery,precise_capture_data_ready,photo_taken,vf_stop]
7:

//Get setting choices
//{"msg_id":9,"param":"video_resolution","token":1}
//"param" - The key you want choices for
9:
/*
{ "rval": 0, "msg_id": 9, "param": "video_resolution", "permission": "settable", "options": [ "1920x1080 60P 16:9", "1920x1080 30P 16:9", "1920x1080 48P 16:9", "1920x1080 24P 16:9", "2304x1296 30P 16:9", "1280x960 60P 4:3", "1280x960 48P 4:3", "1280x720 60P 16:9", "1280x720 48P 16:9", "1280x720 120P 16:9", "848x480 240P 16:9" ] }
"options" - Available options for requested key, in this example "video_resolution"
*/

//change zoom level
//'{"msg_id":14,"type":"fast","param":"%s"}' %(self.ZoomLevelValue)
14:

//get zoom level
//{"msg_id":15,"type":"current"}
15:

// Get Battery level
//{"msg_id":13,"token":1}
13:
/*
{"rval":0,"msg_id":13,"type":"adapter","param":"100"}
"param" - Battery level in percent
"type" - adapter or battery
*/

//Camera Connected setup/update token.
//{"msg_id":257,"token":0}
//{msg_id: 257, token: 0, heartbeat: 1}
257:
/*
{ "msg_id": 7, "type": "vf_stop" }
{ "rval": 0, "msg_id": 257, "param": 1 }
"param" - Your token, you need to pass it in later requests.
Messages with id 7 are status updates:
"vf_stop" - ????
*/

//stop session clear token
258:

// Reset start VF
259:
//enable live stream

// stop VF
260:

// start recording
513:
/**
if "rval":-21
if "rval":-27, means error occured (Probably sdcard is missing/busy)
*/

// stop recording
514:
/**
rval: -14,
*/

// Get Record Time
515:

// trigger shutter
//{"msg_id":769,"token":1}
769:
/**
{"rval":0,"msg_id":769}
{ "msg_id": 7, "type": "start_photo_capture" ,"param":"precise quality;off"}
{ "msg_id": 7, "type": "precise_capture_data_ready" }
{ "msg_id": 7, "type": "photo_taken" ,"param":"/tmp/fuse_d/DCIM/127MEDIA/YDXJ0373.jpg"}
{ "msg_id": 7, "type": "vf_start" }

if "rval":-21
if "rval":-27, means error occured (Probably sdcard is missing/busy)

"rval" - When this equals 0, that means everything is ok. Messages with id 7 are status updates:
"start_photo_capture" - Camera is taking photo
"precise_capture_data_ready" - Photo taken, camera is processing it.
"photo_taken" - Photo has been saved to sdcard, you have path to it in "param"
"vf_start" - ?????
*/

//timelapse photo
//if precise_cont_capturing=on then send msg_id 770 for timelapse
770:

// Get Thumb?
//param: filename, type: any string?
//# > {"msg_id": 1025, "param": "/tmp/fuse_d/DCIM/129MEDIA/YDXJ2007.jpg", "type": "foo"}
//# < { rval: 0, msg_id: 1025, size: 1673, type: 'thumb', md5sum: '5f4eb3f0743b2c2cf718a8399828053e' }
//# sends data over transfer socket
1025:

// Get File/media Info
//# > {"msg_id": 1026, "param": "/tmp/fuse_d/DCIM/129MEDIA/YDXJ2007.jpg"}
//# < { rval: 0, msg_id: 1026, size: 2711430, date: '2016-06-17 02:28:12', resolution: '4608x2592', media_type: 'img' }
1026:

// unknown
//# param: filename, type: any integer?
//# > {"msg_id": 1027, "param": "/tmp/fuse_d/DCIM/129MEDIA/YDXJ2007.jpg", "type": 100}
//# < { rval: 0, msg_id: 1027
1027:

//delete file
1281:

//get file listing
//{msg_id: 1282, param: "#{ dirname } -S -D"}
1282:

//change dir
1283:

//download file size
1285:

//unknown - maybe write
//{msg_id: 1286, param: chunk.filename, offset, size, md5sum}
//Maybe can enable telnet support?
//{"msg_id":1283,"token":%s,"param":"."}
//{"msg_id":1283,"token":%s,"param":"\/tmp\/fuse_d"}
//{"msg_id":1286,"token":%s,"param":"enable_info_display.script", "offset":0, "size":0, "md5sum":"d41d8cd98f00b204e9800998ecf8427e"}}
//{"msg_id":2,"token":%s, "type":"dev_reboot", "param":"on"}
1286:

//unknown.. Displayed if I tried to reconnect and get a new socket when already connected.
//"change different app msg_id: 1793"
1793:

//sdcard type?
16777217:

//capture photo
//{msg_id: 16777220, param: 'precise quality;off'}
16777220:

//last captured photo? - { rval: 0, msg_id: 16777236, param: '/tmp/fuse_d/DCIM/100MEDIA/YDXJ0003.jpg' }
16777236:

//unknown
//{ rval: 0, msg_id: 16777237, param: '7743' }
16777237:

//dumps firmware log to /DCIM/firmware.log
//{ rval: 0, msg_id: 16777242, error: '-2' } / { rval: 0, msg_id: 16777242, param: '/DCIM/firmware.log' }
16777242:

**Comment by Debiprasad-1** [comment]
how to delete a image file from a camera sd card
