### ISSUE TITLE
Amarella A12 Commands 

### ISSUE THREAD

**Issue by natheemy** [jnordberg/yichan#2]
Hello mates, 

I am trying to access WiFi camera Socket using commands. The commands such as

1.Start session - {"msg_id":257,"token":0}

2.Change Directory - {"msg_id":1283,"token":1,"param":"/tmp/sd0/DCIM/180523000"}

3.List File - {"msg_id":1282,"token":1}

works fine.

When I am trying to download the file by sending command

{"msg_id":1285,"offset":0,"param":"AMBA0165.MP4","fetch_size":0,"token":1}

in port 7878 and listening to port 8787 to download the file, I am getting the response

{"rval":0,"msg_id":1285,"rem_size":0,"size":0} but expected response is

{"rval":0,"msg_id":1285,"rem_size":10524,"size":10524}

So I am not receiving a file from the camera.

Could anyone please help me to fix this problem.

**Comment by jnordberg** [comment]
Have a look at the source, the file stream implementation shows you how it's done

**Comment by natheemy** [comment]
`    public void sendCommand(final String data, final IResponseCallback responseCallback) {

        new Thread(new Runnable() {
            @Override
            public void run() {
             IResponseCallback iResponseCallback = responseCallback;

                Socket mSocket = new Socket();
                try {
                    mSocket.connect(new InetSocketAddress(ServerURL.CamURL, ServerURL.CamPORT), ServerURL.TIMEOUT);
                    BufferedOutputStream outputStream = new BufferedOutputStream(mSocket.getOutputStream());
                    BufferedInputStream inputStream = new BufferedInputStream(mSocket.getInputStream());
                    DataInputStream in = new DataInputStream(mSocket.getInputStream());
                    byte[] buff = new byte[256];
                    int len = 0;
                    String msg = null;
                    outputStream.write(data.getBytes());
                    outputStream.flush();
                    while ((len = inputStream.read(buff)) != -1) {
                        msg = new String(buff, 0, len);
                        Log.d("SendCommand", "Response is : "+msg);
                        sendResponse(msg,iResponseCallback);
                    }
                    outputStream.close();
                    inputStream.close();
                    mSocket.close();
                } catch (IOException e) {
                    // sendResponse(e.getMessage(), responseCallback);
                }
            }
        }).start();
    }`

Thanks. please review it.
